apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: boxco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: 192.168.49.2:30500/notification-service:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: NOTIFICATION_MODE
          value: "log"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: boxco
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: notification-service
