apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-api
  namespace: boxco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipment-api
  template:
    metadata:
      labels:
        app: shipment-api
    spec:
      containers:
      - name: shipment-api
        image: 192.168.49.2:30500/shipment-api:scenario-2
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: DYNAMODB_ENDPOINT
          value: "http://dynamodb:8000"
        - name: DYNAMODB_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: "local"
        - name: AWS_SECRET_ACCESS_KEY
          value: "local"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: SCENARIO
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: shipment-api
  namespace: boxco
  labels:
    app: shipment-api
spec:
  type: NodePort
  ports:
  - name: http
    port: 3002
    targetPort: 3002
    nodePort: 30002
  selector:
    app: shipment-api
